import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const DATE_WINDOWS = [
    { value: '3M', label: '3 Months' },
    { value: '6M', label: '6 Months' },
    { value: '12M', label: '12 Months' },
    { value: 'ALL', label: 'All Time' },
    { value: 'CUSTOM', label: 'Custom' },
];
export function FilterPanel({ includeExcluded, problematicOnly, dateWindow, dateFrom, dateTo, riskFilter, onIncludeExcludedChange, onProblematicOnlyChange, onDateWindowChange, onCustomDateRangeChange, onRiskFilterChange, }) {
    return (_jsxs("div", { className: "bg-white border border-stone-200 rounded-xl p-4 flex flex-wrap items-end gap-6", children: [_jsxs("div", { className: "flex flex-col gap-1.5", children: [_jsx("span", { className: "text-xs font-semibold text-stone-500 uppercase tracking-wide", children: "Period" }), _jsx("div", { className: "flex gap-1", children: DATE_WINDOWS.map(({ value, label }) => (_jsx("button", { onClick: () => onDateWindowChange(value), className: `px-3 py-1.5 rounded text-sm font-medium transition-colors ${dateWindow === value
                                ? 'bg-stone-900 text-white'
                                : 'bg-stone-100 text-stone-600 hover:bg-stone-200'}`, children: label }, value))) }), dateWindow === 'CUSTOM' && (_jsxs("div", { className: "flex items-center gap-2 mt-1", children: [_jsx("input", { type: "date", value: dateFrom ?? '', onChange: (e) => onCustomDateRangeChange(e.target.value, dateTo ?? ''), className: "text-sm border border-stone-200 rounded-lg px-2 py-1 outline-none focus:border-amber-400" }), _jsx("span", { className: "text-stone-400 text-sm", children: "\u2192" }), _jsx("input", { type: "date", value: dateTo ?? '', onChange: (e) => onCustomDateRangeChange(dateFrom ?? '', e.target.value), className: "text-sm border border-stone-200 rounded-lg px-2 py-1 outline-none focus:border-amber-400" })] }))] }), _jsxs("div", { className: "flex flex-col gap-1.5", children: [_jsx("span", { className: "text-xs font-semibold text-stone-500 uppercase tracking-wide", children: "Risk" }), _jsx("div", { className: "flex gap-1", children: ['all', 'false_low', 'false_high'].map((v) => (_jsx("button", { onClick: () => onRiskFilterChange(v), className: `px-3 py-1.5 rounded text-sm font-medium transition-colors ${riskFilter === v ? 'bg-stone-900 text-white' : 'bg-stone-100 text-stone-600 hover:bg-stone-200'}`, children: v === 'all' ? 'All' : v === 'false_low' ? 'False Low (Red)' : 'False High (Yellow)' }, v))) })] }), _jsxs("div", { className: "flex flex-col gap-2", children: [_jsx("span", { className: "text-xs font-semibold text-stone-500 uppercase tracking-wide", children: "Filters" }), _jsxs("label", { className: "flex items-center gap-2 cursor-pointer select-none", children: [_jsx("input", { type: "checkbox", checked: problematicOnly, onChange: (e) => onProblematicOnlyChange(e.target.checked), className: "w-4 h-4 accent-amber-400 cursor-pointer" }), _jsx("span", { className: "text-sm text-stone-700", children: "Problematic only" })] }), _jsxs("label", { className: "flex items-center gap-2 cursor-pointer select-none", children: [_jsx("input", { type: "checkbox", checked: includeExcluded, onChange: (e) => onIncludeExcludedChange(e.target.checked), className: "w-4 h-4 accent-amber-400 cursor-pointer" }), _jsx("span", { className: "text-sm text-stone-700", children: "Include Streichresultate" })] })] })] }));
}
